cartoBack/app/src/Entity/Site.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SiteRepository")
 */
class Site
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float", precision=10, scale=0, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $libelle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $rue;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code_ape;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ca;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filiere;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $sujet;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poste;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(?string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getCodeApe(): ?string
    {
        return $this->code_ape;
    }

    public function setCodeApe(?string $code_ape): self
    {
        $this->code_ape = $code_ape;

        return $this;
    }

    public function getCa(): ?string
    {
        return $this->ca;
    }

    public function setCa(?string $ca): self
    {
        $this->ca = $ca;

        return $this;
    }

    public function getFiliere(): ?string
    {
        return $this->filiere;
    }

    public function setFiliere(?string $filiere): self
    {
        $this->filiere = $filiere;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSujet(): ?string
    {
        return $this->sujet;
    }

    public function setSujet(?string $sujet): self
    {
        $this->sujet = $sujet;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(?string $poste): self
    {
        $this->poste = $poste;

        return $this;
    }
}

cartoBack/app/src/Form/SiteType.php
<?php

namespace App\Form;

use App\Entity\Site;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class SiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('longitude')
            ->add('latitude')
            ->add('libelle')
            ->add('ville')
            ->add('numero')
            ->add('rue')
            ->add('cp')
            ->add('code_ape')
            ->add('ca')
            ->add('filiere')
            ->add('date')
            ->add('sujet')
            ->add('poste')
            ->add('save', SubmitType::class, 
                ['label' => 'Créer Entreprise'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Site::class,
        ]);
    }
}

cartoBack/app/src/Controller/SiteController.php
<?php

namespace App\Controller;

use App\Entity\Site;
use App\Form\SiteType;
use Doctrine\DBAL\Schema\View;
use App\Repository\SiteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;



class SiteController extends AbstractController
{

    /**
     * @Route("/index", name="index")
     */
    public function index(SiteRepository $siteRepository)
    {
        return $this->render('site/index.html.twig', [
            'controller_name' => 'Liste des sites',
            'sites' => $siteRepository->findAll()
        ]);
    }
    /**
     * @Route("/newsite", name="newsite")
     */
    public function newsite(Request $request, EntityManagerInterface $entityManager)
    {
        $site = new Site();
        $form = $this->createForm(SiteType::class, $site);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $site = $form->getData();

            $entityManager->persist($site);
            $entityManager->flush();
        }
        return $this->render('site/new.html.twig', [
            'form' => $form->createView()
        ]);
    }
    /**
     * @Route("/delete/{id}", name="delete_site")
     */
    public function delete(Site $site,Request $request, EntityManagerInterface $entityManager,SiteRepository $siteRepository)
    {
            $entityManager->remove($site);
            $entityManager->flush();
            return $this->render('site/index.html.twig', [
                'controller_name' => 'Liste des sites',
                'sites' => $siteRepository->findAll()
            ]);
    }
    /**
     * @Route("/update/{id}", name="update_site")
     */
    public function update(Site $site,Request $request, EntityManagerInterface $entityManager,SiteRepository $siteRepository)
    {
        $form = $this->createForm(SiteType::class, $site);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $site = $form->getData();
            $entityManager->persist($site);
            $entityManager->flush();
        }
        return $this->render('site/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/site/geolocalisation", name="geolocalisation", methods="GET")
     */
    public function geolocalisation(Request $request, SiteRepository $siteRepository)
    {
        $featuresType='Feature';
        $featureType='Point';
        $espg = 'EPSG:3857';
        $crsType = 'name';
        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);
        $siteListe = $siteRepository->findAll();
        foreach ($siteListe as $site) {
            $adresse = $site->getNumero(). " " .$site->getRue(). " " .$site->getCp()." ".$site->getVille();
            $features[] = array('type' => $featuresType,
                                'geometry' => array('type' => $featureType,
                                                    'coordinates' => [$site->getLongitude(), $site->getLatitude()]),
                                'properties'=>array('adresse'=>$adresse,
                                                    'libelle'=>$site->getLibelle(),
                                                    'poste'=>$site->getPoste(),
                                                    'sujet'=>$site->getSujet(),
                                                    'filiere'=>$site->getFiliere(),
                                                    'date'=>$site->getDate(),
                                                    'code_APE'=>$site->getCodeApe(),
                                                    'CA'=>$site->getCa() 
                                ));
        }
        $geoJsonObject = array('type' => 'FeatureCollection', 'crs' => array('type' => $crsType, 'properties' => array('name' =>  $espg)), 'features' => $features);
        $json = $serializer->serialize($geoJsonObject, 'json');
        $response = JsonResponse::fromJsonString($json, Response::HTTP_OK, ['Access-Control-Allow-Origin' => '*']);
        return $response;
    }
}

cartoBack/app/templates/site/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SiteController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
 <h1>{{ controller_name }} : </h1>
<div class="col-1"></div>
  <div class="col-10">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Nom</th>
            <th scope="col">longitude</th>
            <th scope="col">latitude</th>
            <th scope="col">ville</th>
            <th scope="col">N°</th>
            <th scope="col">rue</th>
            <th scope="col">cp</th>
            <th scope="col">code_ape</th>
            <th scope="col">ca</th>
            <th scope="col">filiere</th>
            <th scope="col">date</th>
            <th scope="col">sujet</th>
            <th scope="col">poste</th>
            <th scope="col">action</th>
          </tr>
        </thead>
        <tbody>
            {% for site in sites %}
                <tr>
                    <th scope="row">{{site.libelle}}</th>
                    <td>{{site.longitude}}</td>
                    <td>{{site.latitude}}</td>
                    <td>{{site.ville}}</td>
                    <td>{{site.numero}}</td>
                    <td>{{site.rue}}</td>
                    <td>{{site.cp}}</td>
                    <td>{{site.codeApe}}</td>
                    <td>{{site.ca}}</td>
                    <td>{{site.filiere}}</td>
                    <td>{{site.date|date("m/d/Y")}}</td>
                    <td>{{site.sujet}}</td>
                    <td>{{site.poste}}</td>
                    <td>
                        <form action={{ path('delete_site', {'id': site.id}) }} method="POST">
                          <button type="submit">Supprimer</button><br>
                        </form>   
                        <form action={{ path('update_site', {'id': site.id}) }} method="POST">
                          <button type="submit">Update</button><br>
                        </form>  
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
</div>
<div class="col-1"></div>
{% endblock %}

cartoBack/app/templates/site/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SiteController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {{form(form)}}
    {{ form_errors(form) }}
</div>
{% endblock %}